### ISSUE TITLE
PostgreSQL database URL

### ISSUE THREAD

**Issue by Halon2** [jz-software/telegram-forwarder#5]
I've never worked with PostgreSQL before, do you have a guide for setting it up and getting the URL for the config?

**Comment by JMax45** [comment]
The installation process may vary depending on your system. Here's a link that might help you: https://www.postgresqltutorial.com/install-postgresql/.

The database url is composed like this: postgres://{user}:{password}@{hostname}:{port}/{database-name}
Replace the fields with the corresponding values. The default port is 5432.

**Comment by Halon2** [comment]
> The installation process may vary depending on your system. Here's a link that might help you: https://www.postgresqltutorial.com/install-postgresql/.
> 
> The database url is composed like this: postgres://{user}:{password}@{hostname}:{port}/{database-name}
> Replace the fields with the corresponding values. The default port is 5432.

Thank you! 
I've filled in the details but I'm running into another error after using npm start:

`
(node:6999) UnhandledPromiseRejectionWarning: error: database "forwarding " does not exist
    at Parser.parseErrorMessage (/home/debian/telegram-forwarder/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/home/debian/telegram-forwarder/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/debian/telegram-forwarder/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.stream.on (/home/debian/telegram-forwarder/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:6999) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6999) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6999) UnhandledPromiseRejectionWarning: Error: 404: Not Found
    at buildConfig.then.then.then.then (/home/debian/telegram-forwarder/node_modules/telegraf/core/network/client.js:281:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6999) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
Launch failed
Error: 404: Not Found
    at buildConfig.then.then.then.then (/home/debian/telegram-forwarder/node_modules/telegraf/core/network/client.js:281:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
client process ended
`

**Comment by JMax45** [comment]
Seems like the "forwarding" database doesn't exist. You can create it with `CREATE DATABASE forwarding;` from the psql program.

**Comment by Halon2** [comment]
> CREATE DATABASE forwarding

Already did that:
`
postgres-# \l
                                  List of databases
    Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
------------+----------+----------+-------------+-------------+-----------------------
 forwarding | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/postgres         +
            |          |          |             |             | postgres=CTc/postgres+
            |          |          |             |             | localu=CTc/postgres
`

Still getting the same error

**Comment by Halon2** [comment]
I've reinstalled my Ubuntu server, I'm getting a Failed building wheel for psycopg2.
Would psycopg2-binary also work?
